version: "3.8"

services:
  demo:
    build:
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/demo
      - SPRING_DATASOURCE_USERNAME=demo
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - demo-network
    depends_on:
      - postgres

  my-flutter-app:
    build:
      context: ./my_flutter_app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - demo-network
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    networks:
      - demo-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  demo-network:
    driver: bridge
volumes:
  postgres_data:
    driver: local